### ISSUE TITLE
nm-applet executed twice in i3 config

### ISSUE THREAD

**Issue by H4ppy-04** [VidFurlan/Dotfiles#2]
I noticed a small redundancy that may have been overlooked; `nm-applet` is called twice in the i3 config. Once as part of the default i3 configuration, and twice when called with other startup applications.

https://github.com/VidFurlan/dotfiles/blob/f6043b4abebb09dbca9ee2de6bd41619a8e938c1/desktop/i3/config#L37
 > Called on `line 37` as part of the default i3 configuration.

https://github.com/VidFurlan/dotfiles/blob/f6043b4abebb09dbca9ee2de6bd41619a8e938c1/desktop/i3/config#L227
> Called on `line 227` when also calling other startup applications.

**Comment by VidFurlan** [comment]
Thanks for spotting it.
Removed the redundant line.
